######################################################################
# Automatically generated by qmake (3.0) ?? ??? 9 18:00:40 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = damFileApiProto
INCLUDEPATH += .

# Input
HEADERS += fileapi.h types.h
SOURCES += fileapi.cpp fileapitests.cpp
